### PR TITLE
Add ability to set SetTemperature to CurrentTemperature +/- offset

### PR DESCRIPTION
**Pull request by RaimondB**
Added t+ and t- specifiers to set the SetPoint offset to the current temperature.
Also elaborated the reported statusses to be able to better inform the client on the results.

### CODE REVIEW

**Comment by robertklep** [comment]
Thanks!

Since this feature is so new (only published yesterday), I'm okay with a new scheme altogether. Something like this:
```
current + 2
current - 2
target + 2
target - 2
```

Would make it easier to remember.

**Comment by RaimondB** [comment]
Ok, I chose this schema because of backwards compatibility. The feature basically offers a way to choose a base and offset to set the new setpoint. Maybe it is best keep the terminology consistent and use the terms of the Status command. We could even make it dynamic so that we do the lookup in status with this base-term. (But that might be too much). E.g.

```
in house temp + 2 
temp setpoint + 2

```
or we could change Status to include the terms "current" and "target" so it is clear what is meant with them.

Below the interesting terms from the current status command.

```
'in house temp'               : IHT (Number),
'temp setpoint'               : TSP (Number),
'temp override temp setpoint' : TOT (Number),
'temp manual setpoint'        : MMT (Number),
'outdoor temp' 
```

**Comment by robertklep** [comment]
Using the same names from the status is a good idea (although they're not very intuitive, it makes more sense than introducing 'current' and 'target').

Let me know if you want to add this functionality to your PR, or if I should implement it :)

**Comment by RaimondB** [comment]
Because logic is also applied in the current code on the used setpoint, i decided to go with the names "in house temp" and "setpoint".
It will parse with and without spaces.

@robertklep if you are okay with this version could you merge it so I can use it in the node-red node?

**Comment by robertklep** [comment]
Sorry it took a while, but I just published `nefit-easy-commands@3.0.4` :)

**Pull request merged**
